### ISSUE TITLE
request help

### ISSUE THREAD

**Issue by montyfert** [techman83/homeautomation-pwmlights#1]
hi i am new to tasmota i'm trying to controll a pwm fan depending on the temperature i have a wemos d1 mini and conectedx the pwm fan pwm wire to gpio 14 and can controll the speed using pwm 100 up to pwm 1000 for the speed,
i have a ds1820b sensor conected to pin d1 and can read the temperature  from it but would like to have the speed change depending on the temperature preferably pwm 100 at 28C and pwm 1000 at 31C.
but dont have a clue how to acheive it . 
its to controll the temperature of my 3d printer enclosure .
any sugestions would be great, thanks
martin

**Comment by techman83** [comment]
Probably ask over here -> https://github.com/arendst/Tasmota/discussions
